[appliance] create just one SSL CA certificate as used in default apache config

diff --git a/dist/obsapisetup b/dist/obsapisetup
--- a/dist/obsapisetup
+++ b/dist/obsapisetup
@@ -149,7 +149,7 @@ case "$1" in
 		fi
 
                 if [ ! -e /etc/ssl/private/server.key -a ! -e /etc/ssl/certs/server.crt -a ! -e /etc/ssl/private/server.pem ]; then
-                        if [ ! -e /obs/certs/server.$FQHOSTNAME.pem ]; then
+                        if [ ! -e /obs/certs/server.$FQHOSTNAME.created ]; then
                                # setup ssl certificates (NOT protected with a passphrase)
                                echo "Creating a default SSL certificate for the server, please replace it with your version in /obs/certs directory..."
                                # reuse signing key even if hostname changed
@@ -158,7 +158,7 @@ case "$1" in
                                    openssl genrsa -out /obs/certs/server.key 1024
                                fi
                                # hostname specific certs - survive intermediate hostname changes
-                               if [ ! -e /obs/certs/server.$FQHOSTNAME.pem ] ; then
+                               if [ ! -e /obs/certs/server.pem ] ; then
                                    # This is just a dummy SSL certificate, but it has a valid hostname. Admin can replace it with his version.
 			           echo "CC
 Test State or Province
@@ -169,15 +169,20 @@ $FQHOSTNAME
 test@email.address
 
 
-"                                | openssl req -new -key /obs/certs/server.key -out /obs/certs/server.$FQHOSTNAME.csr >& /dev/null
-                                   openssl x509 -req -days 365 -in /obs/certs/server.$FQHOSTNAME.csr -signkey /obs/certs/server.key -out /obs/certs/server.$FQHOSTNAME.crt
-                                   cat /obs/certs/server.key /obs/certs/server.$FQHOSTNAME.crt > /obs/certs/server.$FQHOSTNAME.pem
+"                                | openssl req -new -key /obs/certs/server.key -out /obs/certs/server.csr >& /dev/null
+                                   openssl x509 -req -days 365 -in /obs/certs/server.csr -signkey /obs/certs/server.key -out /obs/certs/server.crt
+                                   cat /obs/certs/server.key /obs/certs/server.crt > /obs/certs/server.pem
+                                   touch /obs/certs/server.$FQHOSTNAME.created
+                               else
+                                 echo "ERROR: SSL CAs in /obs/certs exists, but were not created for your hostname"
+                                 exit 1
                                fi
                         fi
                         # use certificates from /obs (LVM ?) partition
-                        ln -s /obs/certs/server.key /etc/ssl/private/server.key
-                        ln -s /obs/certs/server.$FQHOSTNAME.crt /etc/ssl/certs/server.crt
-                        ln -s /obs/certs/server.$FQHOSTNAME.pem /etc/ssl/private/server.pem
+                       # this was only needed for lighttpd
+                       #ln -s /obs/certs/server.key /etc/ssl/private/server.key
+                       #ln -s /obs/certs/server.$FQHOSTNAME.crt /etc/ssl/certs/server.crt
+                       #ln -s /obs/certs/server.$FQHOSTNAME.pem /etc/ssl/private/server.pem
                 fi
 
                 cd $webuidir
