[dist] Unhardcoded mysql datadir path. webui db created by rake.

diff --git a/dist/obsapisetup b/dist/obsapisetup
--- a/dist/obsapisetup
+++ b/dist/obsapisetup
@@ -61,6 +61,14 @@ if [ "$?" != "0" ]; then
   USEIP=$FQHOSTNAME
 fi
 
+#export datadir to check that needed db's exist
+grep '^datadir' /etc/my.cnf > /dev/null 2>&1
+if [ $? -gt 0 ]; then
+   echo "Can't export datadir variable from /etc/my.cnf"
+   exit 1
+fi
+export $(grep '^datadir=' /etc/my.cnf)
+
 rc_reset
 case "$1" in
 	start)
@@ -120,10 +128,9 @@ case "$1" in
 		OBSVERSION=`rpm -q --qf '%{VERSION}' obs-server`
 		OS=`head -n 1 /etc/SuSE-release`
                 RUN_INITIAL_SETUP=""
-                if [ ! -e /obs/MySQL/api_production ]; then
+                if [ ! -e "$datadir"/api_production ]; then
 			echo -n "Initialize MySQL databases (first time only)"
 			mysqladmin -u root create api_production
-			mysqladmin -u root create webui_production
 			mysqladmin -u root password "opensuse"
                         RUN_INITIAL_SETUP="true"
 		fi
