[dist] create an initrd also when no LVM is used

diff --git a/dist/obsstoragesetup b/dist/obsstoragesetup
--- a/dist/obsstoragesetup
+++ b/dist/obsstoragesetup
@@ -84,7 +84,7 @@ case "$1" in
 		fi
 
 		# support usage of lvm on md devices
-                if [ -x /sbin/mdadm ]; then
+                if [ -x /sbin/mdadm -a -x /etc/init.d/boot.lvm ]; then
 			/sbin/mdadm --assemble --scan
 			/etc/init.d/boot.lvm start
 		fi
@@ -238,91 +238,92 @@ EOF
 			pvs=( $pvs )
 			pv_count=${#pvs[@]}
 			PE_SIZE=`vgdisplay -c OBS | cut -d: -f13`
-			[ "0$PE_SIZE" -gt 0 ] || exit 0
+			if [ "0$PE_SIZE" -gt 0 ]; then
 
-			if [ -z "$OBS_WORKER_CACHE_SIZE" ]; then
-				# 25 GB sounds like a good default for cache.
-				OBS_WORKER_CACHE_SIZE=$(( 25 * 1024 ))
-			fi
-			OBS_WORKER_CACHE_SIZE=`round_down_to_pe $OBS_WORKER_CACHE_SIZE $PE_SIZE`
-
-			if [ -z "$OBS_WORKER_SWAP_SIZE" ]; then
-				OBS_WORKER_SWAP_SIZE=512
-			fi
-			OBS_WORKER_SWAP_SIZE=`round_down_to_pe $OBS_WORKER_SWAP_SIZE $PE_SIZE`
-
-			if [ -z "$OBS_WORKER_ROOT_SIZE" ]; then
-				VG_SIZE=`vgdisplay -c OBS | awk -F':' '{print( int(int($12) / 1024) )}'`
-				VG_SIZE=$(( $VG_SIZE - $OBS_WORKER_CACHE_SIZE - ( $NUM * $OBS_WORKER_SWAP_SIZE ) ))
-				OBS_WORKER_ROOT_SIZE=$(( $VG_SIZE / $NUM ))
-				if test $OBS_WORKER_ROOT_SIZE -lt $(( 4 * 1024 )); then
-					echo "ERROR: Not enough space for worker root LVs, just $OBS_WORKER_ROOT_SIZE MB, but at least 4 GB needed."
-					exit 1
+				if [ -z "$OBS_WORKER_CACHE_SIZE" ]; then
+					# 25 GB sounds like a good default for cache.
+					OBS_WORKER_CACHE_SIZE=$(( 25 * 1024 ))
 				fi
-			fi
-			OBS_WORKER_ROOT_SIZE=`round_down_to_pe $OBS_WORKER_ROOT_SIZE $PE_SIZE`
+				OBS_WORKER_CACHE_SIZE=`round_down_to_pe $OBS_WORKER_CACHE_SIZE $PE_SIZE`
 
-			if test "$NUM" -ge "$pv_count"; then
-				# More or equal build instances than disks
-				# create LV's and try to distribute them on PV's best as possible
-				o1=0
-				o2=1
-				# MAGIC AT WORK! we append the first items here for the code later to find a 2nd and 3rd offset in the loop
-				pvs=( ${pvs[*]} ${pvs[0]} ${pvs[0]})
+				if [ -z "$OBS_WORKER_SWAP_SIZE" ]; then
+					OBS_WORKER_SWAP_SIZE=512
+				fi
+				OBS_WORKER_SWAP_SIZE=`round_down_to_pe $OBS_WORKER_SWAP_SIZE $PE_SIZE`
 
-				pv_idx=0
-				I="0"
-				while test "$NUM" -gt "$I"; do
-					I=$(( $I + 1 ))
-		
-					lverr=$(mktemp)
-					if ! lvcreate -n worker_root_${I} -L ${OBS_WORKER_ROOT_SIZE}M OBS ${pvs[$(( $pv_idx + $o1 ))]} 2> $lverr; then
-						if grep "Insufficient free space" $lverr; then 
-							I=$(( $I - 1 ))
-						else	
-							cat $lverr >&2
-							exit
-						fi
-					else
- 			                        lvcreate -n worker_swap_${I} -L ${OBS_WORKER_SWAP_SIZE}M OBS ${pvs[$(( $pv_idx + $o2 ))]} || exit
+				if [ -z "$OBS_WORKER_ROOT_SIZE" ]; then
+					VG_SIZE=`vgdisplay -c OBS | awk -F':' '{print( int(int($12) / 1024) )}'`
+					VG_SIZE=$(( $VG_SIZE - $OBS_WORKER_CACHE_SIZE - ( $NUM * $OBS_WORKER_SWAP_SIZE ) ))
+					OBS_WORKER_ROOT_SIZE=$(( $VG_SIZE / $NUM ))
+					if test $OBS_WORKER_ROOT_SIZE -lt $(( 4 * 1024 )); then
+						echo "ERROR: Not enough space for worker root LVs, just $OBS_WORKER_ROOT_SIZE MB, but at least 4 GB needed."
+						exit 1
 					fi
-					rm -f $lverr
-		                        pv_idx=$(( $pv_idx + 2 ))
-		                        if [ $pv_idx -eq $pv_count ]; then
-						pv_idx=0
-						# swap offset, so that swap and root partitions are not on same device
-						a=$o1
-						o1=$o2
-						o2=$a
-		                        elif [ $pv_idx -gt $pv_count ]; then
-						pv_idx=1
-		                        fi
-				done
-			else
-				# More disks than build instances
-				# Use striping to boost IO performance
-				I="0"
-				# FIXME: this is a bit too simple, it can't handle float numbers
-				disks_per_instance=$(( $pv_count / $NUM ))
-				while test "$NUM" -gt "$I"; do
-					I=$(( $I + 1 ))
-	
-					DEVS=""
-					J="0"
-					while test "$disks_per_instance" -lt "$J"; do
-						J=$(( $J + 1 ))
-						DEVS="$DEVS ${pvs[$(( $I * $disks_per_instance + $J ))]}"
-					done
-	
-					lvcreate -n worker_root_${I} -L ${OBS_WORKER_ROOT_SIZE}M OBS $DEVS || exit
-		                        lvcreate -n worker_swap_${I} -L ${OBS_WORKER_SWAP_SIZE}M OBS $DEVS || exit
-				done
-			fi
+				fi
+				OBS_WORKER_ROOT_SIZE=`round_down_to_pe $OBS_WORKER_ROOT_SIZE $PE_SIZE`
 
-			# Create cache partition on remaining space
-			#lvcreate -n cache -l 100%FREE OBS || exit
-			lvcreate -n cache -L "${OBS_WORKER_CACHE_SIZE}M" OBS || exit
-			mkfs -text4 /dev/OBS/cache || exit
+				if test "$NUM" -ge "$pv_count"; then
+					# More or equal build instances than disks
+					# create LV's and try to distribute them on PV's best as possible
+					o1=0
+					o2=1
+					# MAGIC AT WORK! we append the first items here for the code later to find a 2nd and 3rd offset in the loop
+					pvs=( ${pvs[*]} ${pvs[0]} ${pvs[0]})
+
+					pv_idx=0
+					I="0"
+					while test "$NUM" -gt "$I"; do
+						I=$(( $I + 1 ))
+				
+						lverr=$(mktemp)
+						if ! lvcreate -n worker_root_${I} -L ${OBS_WORKER_ROOT_SIZE}M OBS ${pvs[$(( $pv_idx + $o1 ))]} 2> $lverr; then
+							if grep "Insufficient free space" $lverr; then 
+								I=$(( $I - 1 ))
+							else	
+								cat $lverr >&2
+								exit
+							fi
+						else
+ 				                        lvcreate -n worker_swap_${I} -L ${OBS_WORKER_SWAP_SIZE}M OBS ${pvs[$(( $pv_idx + $o2 ))]} || exit
+						fi
+						rm -f $lverr
+				                pv_idx=$(( $pv_idx + 2 ))
+				                if [ $pv_idx -eq $pv_count ]; then
+							pv_idx=0
+							# swap offset, so that swap and root partitions are not on same device
+							a=$o1
+							o1=$o2
+							o2=$a
+				                elif [ $pv_idx -gt $pv_count ]; then
+							pv_idx=1
+				                fi
+					done
+				else
+					# More disks than build instances
+					# Use striping to boost IO performance
+					I="0"
+					# FIXME: this is a bit too simple, it can't handle float numbers
+					disks_per_instance=$(( $pv_count / $NUM ))
+					while test "$NUM" -gt "$I"; do
+						I=$(( $I + 1 ))
+	
+						DEVS=""
+						J="0"
+						while test "$disks_per_instance" -lt "$J"; do
+							J=$(( $J + 1 ))
+							DEVS="$DEVS ${pvs[$(( $I * $disks_per_instance + $J ))]}"
+						done
+	
+						lvcreate -n worker_root_${I} -L ${OBS_WORKER_ROOT_SIZE}M OBS $DEVS || exit
+				                lvcreate -n worker_swap_${I} -L ${OBS_WORKER_SWAP_SIZE}M OBS $DEVS || exit
+					done
+				fi
+
+				# Create cache partition on remaining space
+				#lvcreate -n cache -l 100%FREE OBS || exit
+				lvcreate -n cache -L "${OBS_WORKER_CACHE_SIZE}M" OBS || exit
+				mkfs -text4 /dev/OBS/cache || exit
+			fi
 		fi
 
 		if [ ! "0$NUM" -gt 0 ]; then
