Merging upstream version 2.7.0.

diff --git a/dist/obsstoragesetup b/dist/obsstoragesetup
--- a/dist/obsstoragesetup
+++ b/dist/obsstoragesetup
@@ -9,7 +9,7 @@
 #
 ### BEGIN INIT INFO
 # Provides:          obsstoragesetup
-# X-Start-Before:    mysql sshd
+# X-Start-Before:    mysql sshd obsapisetup
 # Should-Start:      xendomains haveged
 # Should-Stop:       $none
 # Required-Start:    $network
@@ -21,10 +21,11 @@
 
 . /etc/rc.status
 
-# package or appliance defaults
-if [ -e /etc/sysconfig/obs-server ]; then
-  source /etc/sysconfig/obs-server
-fi
+# BOOTSTRAP_TEST_MODE prevents setup-appliance.sh execution
+# this is also sourcing /etc/sysconfig/obs-server
+export BOOTSTRAP_TEST_MODE=1
+source /usr/lib/obs/server/setup-appliance.sh
+unset BOOTSTRAP_TEST_MODE
 
 # instance defaults
 if [ -e /etc/buildhost.config ]; then
@@ -101,7 +102,7 @@ case "$1" in
 
 				# Find unpartitioned disks and create LVM partition on them
 				for disk in `hwinfo --disk | grep "Device File:" |\
-					cut -f2 -d: | cut -f2 -d" "`;do
+					cut -f2 -d: | cut -f2 -d" " | grep -v /dev/ram`;do
 				        count=0
 				        used=
 				        for i in `sfdisk -l $disk 2>/dev/null | tr -d '*' | grep ^/ |\
@@ -140,6 +141,7 @@ case "$1" in
 			echo "Remove all LVM cache and worker partitions in VG OBS."
 			# Cannot test on existence of "/dev/OBS", in case no LVs in VG OBS have been created!
 			if [ -n "$(vgdisplay -c OBS 2>/dev/null)" ]; then
+				vgchange -ay OBS
 			        lvremove -f /dev/OBS/worker_* /dev/OBS/cache 2>/dev/null
                         else
 				echo "WARNING: The LVM volume group 'OBS' can not be used."
@@ -148,59 +150,47 @@ case "$1" in
 		fi
 
 		echo "Looking for existing OBS Server LVM Volume"
+		[ -d "$backenddir" ] || mkdir -p "$backenddir"
                 if [ -e /dev/OBS/server ]; then
 			mount /dev/OBS/server "$backenddir"
+			if [ -e /usr/lib/obs/server/BSConfig.pm ];then
+				echo "Found BSConfig.pm"
+				if [ -d "$backenddir/run" ]; then
+					echo "Directory '$backenddir/run' exists"
+					# make sure that directories needed by mostly all other daemons are created now
+					# and set proper ownership
+					bsuser=`perl -I/usr/lib/obs/server -MBSConfig -e 'print ( $BSConfig::bsuser || "obsrun" )'`
+					bsgroup=`perl -I/usr/lib/obs/server -MBSConfig -e 'print ( $BSConfig::bsgroup || "obsrun" )'`
+					owner_rundir=`stat -L --printf="%U" "$backenddir/run"`
+					if [ "$owner_rundir" != "root" ];then
+						echo "owner of '$backenddir/run' is $owner_rundir"
+						if [ "$owner_rundir" != "$bsuser" ];then
+							echo "owner $owner_rundir is not configured bsuser '$bsuser'"
+							echo "changing ownership"
+							uid_rundir=`stat -L --printf="%u" "$backenddir/run"`
+							find $backenddir -uid $uid_rundir -exec chown $bsuser:$bsgroup {} \;
+						else 
+							echo "Owner of '$backenddir/run' is '$bsuser'. Nothing to fix!"
+						fi
+					else 
+						echo "Owner of '$backenddir/run' is root. Not changing anything"
+					fi
+				else 
+					echo "Directory '$backenddir/run' not found"
+				fi
+			else
+				echo "No BSConfig found while setting up /dev/OBS/server"
+			fi
 			obs_server_size=$(( $(lvdisplay -c OBS/server 2>/dev/null | cut -d: -f7) / 2 / 1024 ))
+		else 
+			echo "No logical volume found under /dev/OBS/server"
                 fi
 
-		# Only used if there is a local BSConfig
-		if [ -e /usr/lib/obs/server/BSConfig.pm ]; then
-			# create default gpg key if not existing
-			if [ ! -e "$backenddir"/obs-default-gpg.asc ] && grep -q "^our \$keyfile.*/obs-default-gpg.asc.;$" /usr/lib/obs/server/BSConfig.pm; then
-				echo -n Generating OBS default GPG key ....
-				mkdir -p "$backenddir"/gnupg/phrases
-				chmod -R 0700 "$backenddir"/gnupg
-				cat >/tmp/obs-gpg.$$ <<EOF
-				     %echo Generating a default OBS instance key
-				     Key-Type: DSA
-				     Key-Length: 1024
-				     Subkey-Type: ELG-E
-				     Subkey-Length: 1024
-				     Name-Real: private OBS
-				     Name-Comment: key without passphrase
-				     Name-Email: defaultkey@localobs
-				     Expire-Date: 0
-				     %pubring $backenddir/gnupg/pubring.gpg
-				     %secring $backenddir/gnupg/secring.gpg
-				     %commit
-				     %echo done
-EOF
-				gpg2 --homedir $backenddir/gnupg --batch --gen-key /tmp/obs-gpg.$$
-				gpg2 --homedir $backenddir/gnupg --export -a > "$backenddir"/obs-default-gpg.asc
-				# empty file just for accepting the key
-				touch "$backenddir/gnupg/phrases/defaultkey@localobs"
-			fi
-			# to update sign.conf also after an appliance update
-			if [ -e "$backenddir"/obs-default-gpg.asc ] && ! grep -q "^user" /etc/sign.conf; then
-				# extend signd config
-				echo "user: defaultkey@localobs"   >> /etc/sign.conf
-				echo "server: 127.0.0.1"           >> /etc/sign.conf
-				echo "allowuser: obsrun"           >> /etc/sign.conf
-				echo "allow: 127.0.0.1"            >> /etc/sign.conf
-				echo "phrases: $backenddir/gnupg/phrases" >> /etc/sign.conf
-				echo done
-				rm /tmp/obs-gpg.$$
-				sed -i 's,^# \(our $sign =.*\),\1,' /usr/lib/obs/server/BSConfig.pm
-				sed -i 's,^# \(our $forceprojectkeys =.*\),\1,' /usr/lib/obs/server/BSConfig.pm
-			fi
-			if [ ! -e "$backenddir"/obs-default-gpg.asc ] ; then
-			    sed -i 's,^\(our $sign =.*\),# \1,' /usr/lib/obs/server/BSConfig.pm
-			    sed -i 's,^\(our $forceprojectkeys =.*\),# \1,' /usr/lib/obs/server/BSConfig.pm
-			fi
+                # setup signer and signd if possible
+		prepare_obssigner
 
-                        # Force mysql to update database. FIXME: only on version update
-                        [ -d "$backenddir"/MySQL/ ] && touch "$backenddir"/MySQL/.run-mysql_upgrade
-		fi
+                # Force mysql to update database. FIXME: only on version update
+		[ -d "$backenddir"/MySQL/ ] && touch "$backenddir"/MySQL/.run-mysql_upgrade
 
 		if [ "$OBS_SETUP_WORKER_PARTITIONS" = "take_all" -o "$OBS_SETUP_WORKER_PARTITIONS" = "use_obs_vg" ]; then
 			if [ 0"$OBS_WORKER_INSTANCES" -gt 0 ]; then
@@ -237,6 +227,7 @@ EOF
 					pvs="$pvs $i"
 				fi
 			done
+			disks_per_instance=1
 			pvs=( $pvs )
 			pv_count=${#pvs[@]}
 			PE_SIZE=`vgdisplay -c OBS | cut -d: -f13`
@@ -255,11 +246,25 @@ EOF
 
 				if [ -z "$OBS_WORKER_ROOT_SIZE" ]; then
 					VG_SIZE=`vgdisplay -c OBS | cut -d: -f16`
-					VG_SIZE=$(( $VG_SIZE * ( $PE_SIZE / 1024 ) ))
-					VG_SIZE=$(( $VG_SIZE - ${obs_server_size:-0} - $OBS_WORKER_CACHE_SIZE - ( $NUM * $OBS_WORKER_SWAP_SIZE ) ))
-					OBS_WORKER_ROOT_SIZE=$(( $VG_SIZE / $NUM ))
+					PE_SIZE_IN_MB=$((  $PE_SIZE / 1024 ))
+					VG_SIZE=$(( $VG_SIZE * $PE_SIZE_IN_MB ))
+					OBS_SERVER_SIZE=${obs_server_size:-0}
+					TOTAL_SWAP_SIZE=$(( $NUM * $OBS_WORKER_SWAP_SIZE ))
+					FINAL_VG_SIZE=$(( $VG_SIZE - $OBS_SERVER_SIZE - $OBS_WORKER_CACHE_SIZE - $TOTAL_SWAP_SIZE ))
+					OBS_WORKER_ROOT_SIZE=$(( $FINAL_VG_SIZE / $NUM ))
+					MIN_WORKER_ROOT_SIZE=$(( 4 * 1024 ))
 					if test $OBS_WORKER_ROOT_SIZE -lt $(( 4 * 1024 )); then
 						echo "ERROR: Not enough space for worker root LVs, just $OBS_WORKER_ROOT_SIZE MB, but at least 4 GB needed."
+						echo "NUM=$NUM"
+						echo "VG_SIZE=$VG_SIZE"
+						echo "PE_SIZE=$PE_SIZE"
+						echo "PE_SIZE_IN_MB=$PE_SIZE_IN_MB"
+						echo "OBS_SERVER_SIZE=$OBS_SERVER_SIZE"
+						echo "TOTAL_SWAP_SIZE=$TOTAL_SWAP_SIZE"
+						echo "FINAL_VG_SIZE = $VG_SIZE - $OBS_SERVER_SIZE - $OBS_WORKER_CACHE_SIZE - $TOTAL_SWAP_SIZE"
+						echo "FINAL_VG_SIZE=$FINAL_VG_SIZE";
+						echo "OBS_WORKER_ROOT_SIZE=$OBS_WORKER_ROOT_SIZE"
+						echo "MIN_WORKER_ROOT_SIZE=$MIN_WORKER_ROOT_SIZE"
 						exit 1
 					fi
 				fi
@@ -279,7 +284,13 @@ EOF
 						I=$(( $I + 1 ))
 				
 						lverr=$(mktemp)
-						if ! lvcreate -n worker_root_${I} -L ${OBS_WORKER_ROOT_SIZE}M OBS ${pvs[$(( $pv_idx + $o1 ))]} 2> $lverr; then
+						if ! lvcreate --wipesignatures y -n worker_root_${I} -L ${OBS_WORKER_ROOT_SIZE}M OBS ${pvs[$(( $pv_idx + $o1 ))]} 2> $lverr; then
+							if [ $? -gt 0 ];then
+								echo "An error occured while creating LV"
+								cat $lverr
+							else
+								echo "Creation of worker_root_${I} succeed"
+							fi
 							if grep "Insufficient free space" $lverr; then 
 								I=$(( $I - 1 ))
 							else	
@@ -287,7 +298,13 @@ EOF
 								exit
 							fi
 						else
- 				                        lvcreate -n worker_swap_${I} -L ${OBS_WORKER_SWAP_SIZE}M OBS ${pvs[$(( $pv_idx + $o2 ))]} || exit
+ 				                        lvcreate --wipesignatures y -n worker_swap_${I} -L ${OBS_WORKER_SWAP_SIZE}M OBS ${pvs[$(( $pv_idx + $o2 ))]}
+							if [ $? -gt 0 ];then
+								echo "An error occured while creating LV worker_swap_${I} "
+								exit 1
+							else
+								echo "Creation of worker_swap_${I} succeed"
+							fi
 						fi
 						rm -f $lverr
 				                pv_idx=$(( $pv_idx + 2 ))
@@ -304,9 +321,8 @@ EOF
 				else
 					# More disks than build instances
 					# Use striping to boost IO performance
+					disks_per_instance=$pv_count
 					I="0"
-					# FIXME: this is a bit too simple, it can't handle float numbers
-					disks_per_instance=$(( $pv_count / $NUM ))
 					while test "$NUM" -gt "$I"; do
 						I=$(( $I + 1 ))
 	
@@ -317,19 +333,19 @@ EOF
 							DEVS="$DEVS ${pvs[$(( $I * $disks_per_instance + $J ))]}"
 						done
 	
-						lvcreate -n worker_root_${I} -L ${OBS_WORKER_ROOT_SIZE}M OBS $DEVS || exit
-				                lvcreate -n worker_swap_${I} -L ${OBS_WORKER_SWAP_SIZE}M OBS $DEVS || exit
+						lvcreate --wipesignatures y -n worker_root_${I} -i $disks_per_instance -L ${OBS_WORKER_ROOT_SIZE}M OBS $DEVS || exit
+				                lvcreate --wipesignatures y -n worker_swap_${I} -i $disks_per_instance -L ${OBS_WORKER_SWAP_SIZE}M OBS $DEVS || exit
 					done
 				fi
 
 				# Create cache partition on remaining space
-				#lvcreate -n cache -l 100%FREE OBS || exit
-				lvcreate -n cache -L "${OBS_WORKER_CACHE_SIZE}M" OBS || exit
+				#lvcreate -n cache -i $disks_per_instance -l 100%FREE OBS || exit
+				lvcreate --wipesignatures y -n cache -i $disks_per_instance -L "${OBS_WORKER_CACHE_SIZE}M" OBS || exit
 				mkfs -text4 /dev/OBS/cache || exit
 			fi
 		fi
 
-		if [ ! "0$NUM" -gt 0 ]; then
+		if [ ! "0$NUM" -gt 0 -a -z "$OBS_WORKER_SCRIPT_URL" ]; then
 			exit 0
 		fi
 
@@ -359,11 +375,6 @@ EOF
 				echo "Found KVM virtualization"
 				RUN_VIRT=1
 		                # support virtio
-		                # FIXME: find a better way to do this without getting removed by kiwi again.
-		                if ! grep -q "^INITRD_MODULES=.*virtio_pci virtio_blk" /etc/sysconfig/kernel; then
-		                   sed -i 's,^INITRD_MODULES="\(.*\)",INITRD_MODULES="\1 loop dm-mod dm-snapshot binfmt-misc fuse kqemu squashfs ext2 ext3 ext4 reiserfs nf_conntrack_ipv6 binfmt_misc virtio_pci virtio_blk fat vfat nls_cp437 nls_iso8859-1",' /etc/sysconfig/kernel
-		                   mkinitrd || unset RUN_VIRT
-		                fi
 			else
 				echo "*** NO virtualization found, BUILDING IN UNSECURE ENVIROMENT ***"
 				unset RUN_VIRT
@@ -402,15 +413,17 @@ EOF
 				fi
 			fi
 			echo "OBS_WORKER_JOBS=\"$MYJOBS\"" >> /etc/buildhost.config
-			
-			# Memory which can be used
-			TOTALMEM=$(( `free | sed -n 's/^Mem:[ ]*\([^ ]*\).*/\1/p'` / 1024 ))
-			INSTANCEMEM=$(( $TOTALMEM / ( 2 * $OBS_WORKER_INSTANCES ) ))
-			echo "OBS_INSTANCE_MEMORY=\"$INSTANCEMEM\"" >> /etc/buildhost.config
+
+                        if [ -z "$OBS_INSTANCE_MEMORY" ]; then
+				# Guess how much memory can be used
+				TOTALMEM=$(( `free | sed -n 's/^Mem:[ ]*\([^ ]*\).*/\1/p'` / 1024 ))
+				OBS_INSTANCE_MEMORY=$(( $TOTALMEM / ( 2 * $OBS_WORKER_INSTANCES ) ))
+				echo "OBS_INSTANCE_MEMORY=\"$OBS_INSTANCE_MEMORY\"" >> /etc/buildhost.config
+                        fi
 			if grep ^flags /proc/cpuinfo | egrep -q " (svm|vmx) " && test -n "$RUN_VIRT"; then
                                 # try to use hugetlb on kvm
 				mkdir -p /dev/hugetlbfs # systemd may have mounted it already
-			        HUGETLBINSTANCEMEM=$(( ($INSTANCEMEM * 512) / 1024 )) # 2M page sizes
+			        HUGETLBINSTANCEMEM=$(( ($OBS_INSTANCE_MEMORY * 512) / 1024 )) # 2M page sizes
 			        HUGETLMEM=$(( $HUGETLBINSTANCEMEM * $OBS_WORKER_INSTANCES ))
                                 # register huge table memory pages
                                 echo "$HUGETLMEM" > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
@@ -439,11 +452,23 @@ EOF
 			fi
 		fi
 
+		if [ -e /usr/lib/obs/server -a -e /usr/lib/obs/server/BSConfig.pm ]; then
+			# make sure that directories needed by mostly all other daemons are created now
+			# and set proper ownership
+			bsuser=`perl -I/usr/lib/obs/server -MBSConfig -e 'print ( $BSConfig::bsuser || "obsrun" )'`
+			bsgroup=`perl -I/usr/lib/obs/server -MBSConfig -e 'print ( $BSConfig::bsgroup || "obsrun" )'`
+			[ -d $backenddir/run ] || mkdir -p $backenddir/run
+			[ -d $backenddir/log ] || mkdir -p $backenddir/log
+			# fix ownership
+			chown $bsuser:$bsgroup $backenddir
+		fi
+
 		# offer hook to make random special things in your setup
 		if [ -n "$OBS_WORKER_SCRIPT_URL" ]; then
 			echo "Running special script for this worker from $OBS_WORKER_SCRIPT_URL"
 			curl $OBS_WORKER_SCRIPT_URL > /tmp/osbworkerscript.$$
 			chmod 0755 /tmp/osbworkerscript.$$
+			export OBS_WORKER_DIRECTORY
 			/tmp/osbworkerscript.$$
 			rm /tmp/osbworkerscript.$$
 		fi
