fix to use OBS_WORKER_DIRECTORY

diff --git a/dist/obsstoragesetup b/dist/obsstoragesetup
--- a/dist/obsstoragesetup
+++ b/dist/obsstoragesetup
@@ -19,10 +19,16 @@
 
 . /etc/rc.status
 
+# package or appliance defaults
 if [ -e /etc/sysconfig/obs-server ]; then
   source /etc/sysconfig/obs-server
 else
   source /etc/sysconfig/obs-worker
+fi
+
+# instance defaults
+if [ -e /etc/buildhost.config ]; then
+  source /etc/buildhost.config
 fi
 
 if [ "$OBS_STORAGE_AUTOSETUP" != "yes" ]; then
@@ -36,14 +42,15 @@ link=${base#*[SK][0-9][0-9]}
 
 backenddir=/srv/obs
 
+if [ -z "$OBS_WORKER_DIRECTORY" ]; then
+	OBS_WORKER_DIRECTORY="/OBS.worker"
+fi
+
 rc_reset
 case "$1" in
 	start)
 		# configure sshd if wanted
 		if [ ! -e /root/.ssh/authorized_keys ]; then
-			OBS_ROOT_SSHD_KEY_URL=`sed -n 's,^OBS_ROOT_SSHD_KEY_URL=\(.*\),\1,p' /etc/buildhost.config`
-			OBS_ROOT_SSHD_KEY_URL=${OBS_ROOT_SSHD_KEY_URL#\"}
-			OBS_ROOT_SSHD_KEY_URL=${OBS_ROOT_SSHD_KEY_URL%\"}
 			if [ -n "$OBS_ROOT_SSHD_KEY_URL" ]; then
 				echo "Enabling sshd as requested"
 				[ -e /root/.ssh ] || mkdir /root/.ssh
@@ -52,7 +59,144 @@ case "$1" in
 				rcsshd start
 			fi
 		fi
+
+		if [ "$OBS_SETUP_WORKER_PARTITIONS" = "take_all" ]; then
+			echo "Collect all LVM partitions for the worker"
+			# remove everything first
+			vgreduce --removemissing OBS
+			vgremove -f OBS
+			pvremove `pvdisplay  | grep "PV Name" | awk '{ print $3 }'`
+
+			# Collect all LVM partitions
+			DEVICES=""
+			for i in `sfdisk -l 2>/dev/null | tr -d '*' | grep ^/ |\
+				sed -e s"@\s\+@:@g" | cut -f1,5,6 -d:`;do
+				device=`echo $i | cut -f1 -d:`
+				blocks=`echo $i | cut -f2 -d:`
+				partid=`echo $i | cut -f3 -d:`
+				if [ $blocks = "0" ];then
+				        continue 
+				fi
+				if [ $partid = "8e" ];then
+					pvcreate $device && DEVICES="$DEVICES $device"
+				fi
+			done
+			vgcreate OBS $DEVICES
+			vgscan
+		fi
+
+		if [ "$OBS_SETUP_WORKER_PARTITIONS" = "take_all" -o "$OBS_SETUP_WORKER_PARTITIONS" = "use_obs_vg" ]; then
+			if [ "$OBS_WORKER_INSTANCES" -gt 0 ]; then
+				# got config setting from sysconfig or PXE server
+				NUM="$OBS_WORKER_INSTANCES"
+			else
+				# auto detect max possible instances
+				# start one build backend per CPU by default
+				NUM=`ls -d /sys/devices/system/cpu/cpu[0-9]* | wc -l`
+
+				# but be sure that we have at least 512MB per instance
+				MEMORY=`sed -n 's/^MemTotal:[ ]*\(.*\).kB$/\1/p' /proc/meminfo`
+				if [ $MEMORY -lt $(( $NUM * 512 * 1024 )) ]; then
+					NUM=$(( $MEMORY / ( 1024 * 512 ) ))
+					NUM=$(( $NUM - 1 ))  # for Dom0
+				fi
+			fi
+			if [ ! "0$OBS_WORKER_INSTANCES" -gt 0 ]; then
+				echo "ERROR: OBS worker instances are 0, either miss configuration or not enough resources"
+				exit 1
+			fi
+
+			# Look for PV devices in OBS VG
+			pvs=""
+			for i in `vgdisplay -v OBS 2>/dev/null | grep "PV Name" | awk '{ print $3 }'`; do
+				if [ -L $i ]; then
+					pvs="$pvs `readlink -f $i`"
+				else
+					pvs="$pvs $i"
+				fi
+			done
+			pvs=( $pvs )
+			pv_count_real=${#pvs[@]}
+
+			if [ -z "$OBS_WORKER_CACHE_SIZE" ]; then
+				# 25 GB sounds like a good default for cache.
+				OBS_WORKER_CACHE_SIZE=$(( 25 * 1024 ))
+			fi
+
+			if [ -z "$OBS_WORKER_SWAP_SIZE" ]; then
+				OBS_WORKER_SWAP_SIZE=512
+			fi
+
+			if [ -z "$OBS_WORKER_ROOT_SIZE" ]; then
+				VG_SIZE=`vgdisplay OBS --units M | grep "Free  PE" | sed 's,.* \([^ ]*\)\..*MB$,\1,'`
+				VG_SIZE=$(( $VG_SIZE - $OBS_WORKER_CACHE_SIZE - ( $NUM * $OBS_WORKER_SWAP_SIZE ) ))
+				OBS_WORKER_ROOT_SIZE=$(( $VG_SIZE / $NUM ))
+				if test $OBS_WORKER_ROOT_SIZE -lt $(( 4 * 1024 )); then
+					echo "ERROR: Not enough space for worker root LVs, just $OBS_WORKER_ROOT_SIZE MB, but at least 4 GB needed."
+					exit 1
+				fi
+			fi
+
+			if test "$NUM" -ge "$pv_count_real"; then
+				# More or equal build instances than disks
+				# create LV's and try to distribute them on PV's best as possible
+				o1=0
+				o2=1
+				if [ $pv_count_real -gt 1 ]; then
+					pv_count=$(( ($pv_count_real / 2) * 2 )) # be sure that we have an equal number
+				elif [ $pv_count_real -eq 1 ]; then
+					o2=0
+					pv_count=1
+				else
+					# FIXME: error handling
+					echo "BUG"
+				fi
+				offset=1
+				if [ "$pv_count_real" == "$pv_count" ]; then
+				  offset=0
+				fi
+
+				pv_idx=0
+				I="0"
+				while test "$NUM" -gt "$I"; do
+					I=$(( $I + 1 ))
 		
+					lvcreate -n worker_root_${I} -L ${OBS_WORKER_ROOT_SIZE}M OBS ${pvs[$(( $pv_idx + $o1 + $offset ))]} || exit
+		                        lvcreate -n worker_swap_${I} -L ${OBS_WORKER_SWAP_SIZE}M OBS ${pvs[$(( $pv_idx + $o2 + $offset ))]} || exit
+		                        pv_idx=$(( $pv_idx + 2 ))
+		                        if [ $pv_idx -ge $pv_count ]; then
+						pv_idx=0
+						# swap offset, so that swap and root partitions are not on same device
+						a=$o1
+						o1=$o2
+						o2=$a
+		                        fi
+				done
+			else
+				# More disks than build instances
+				# Use striping to boost IO performance
+				I="0"
+				# FIXME: this is a bit too simple, it can't handle float numbers
+				disks_per_instance=$(( $pv_count_real / $NUM ))
+				while test "$NUM" -gt "$I"; do
+					I=$(( $I + 1 ))
+	
+					DEVS=""
+					J="0"
+					while test "$disks_per_instance" -lt "$J"; do
+						J=$(( $J + 1 ))
+						DEVS="$DEVS ${pvs[$(( $I * $disks_per_instance + $J ))]}"
+					done
+	
+					lvcreate -n worker_root_${I} -L ${OBS_WORKER_ROOT_SIZE}M OBS $DEVS || exit
+		                        lvcreate -n worker_swap_${I} -L ${OBS_WORKER_SWAP_SIZE}M OBS $DEVS || exit
+				done
+			fi
+
+			# Create cache partition on remaining space
+			lvcreate -n cache -l 100%FREE OBS || exit
+		fi
+
 		echo "Looking for OBS Server LVM Volume"
                 if [ -e /dev/OBS/server ]; then
 			[ -d /obs ] || { rm -f /obs; mkdir /obs ; }
@@ -71,8 +215,9 @@ case "$1" in
 
 		echo "Looking for OBS Worker Cache LVM Volume"
                 if [ -e /dev/OBS/cache ]; then
-			mkdir -p /OBS.worker/cache
-			mount /dev/OBS/cache /OBS.worker/cache
+			mkdir -p $OBS_WORKER_DIRECTORY
+			mount /dev/OBS/cache $OBS_WORKER_DIRECTORY
+			mkdir -p $OBS_WORKER_DIRECTORY/cache
                 fi
 
 		echo "Setting up OBS Workers according to LVM Volumes"
@@ -81,10 +226,10 @@ case "$1" in
                 fi
 		
 		echo "### autoconfigured values by obsstoragesetup init script"  > /etc/buildhost.config
-		echo "OBS_WORKER_DIRECTORY=\"/OBS.worker/\"" >> /etc/buildhost.config
-		echo "OBS_CACHE_DIR=\"/OBS.worker/cache\""   >> /etc/buildhost.config
-		CACHEMB=`df -m /OBS.worker/cache | tail -n 1 | sed -n 's,^/dev/[^ ]*[ ]*\([^ ]*\).*,\1,p'`
-		[ -z "$CACHEMB" ] && CACHEMB=`df -m /OBS.worker/cache | tail -n 1 | sed -n 's,[^ ]*[ ]*\([^ ]*\).*,\1,p'`
+		echo "OBS_WORKER_DIRECTORY=\"$OBS_WORKER_DIRECTORY/\"" >> /etc/buildhost.config
+		echo "OBS_CACHE_DIR=\"$OBS_WORKER_DIRECTORY/cache\""   >> /etc/buildhost.config
+		CACHEMB=`df -m /$OBS_CACHE_DIR | tail -n 1 | sed -n 's,^/dev/[^ ]*[ ]*\([^ ]*\).*,\1,p'`
+		[ -z "$CACHEMB" ] && CACHEMB=`df -m /$OBS_CACHE_DIR | tail -n 1 | sed -n 's,[^ ]*[ ]*\([^ ]*\).*,\1,p'`
 		[ -n "$CACHEMB" ] && echo "OBS_CACHE_SIZE=\"$(( $CACHEMB / 2 ))\"" >> /etc/buildhost.config
 		if [ -e /sys/hypervisor/type ] && grep -q xen /sys/hypervisor/type; then
 			echo "Found XEN virtualization"
@@ -111,13 +256,13 @@ case "$1" in
 			[ -e $swap ] || continue
 			if [ -n "$RUN_VIRT" ]; then
 				#prepare xen or kvm setup
-				mkdir -p "/OBS.worker/$name"
-				ln -sf "$i"    "/OBS.worker/$name/root"
-				ln -sf "$swap" "/OBS.worker/$name/swap"
+				mkdir -p "$OBS_WORKER_DIRECTORY/$name"
+				ln -sf "$i"    "$OBS_WORKER_DIRECTORY/$name/root"
+				ln -sf "$swap" "$OBS_WORKER_DIRECTORY/$name/swap"
 			else
 				#plain chroot build
-				mkdir -p "/OBS.worker/$name"
-				mount $i "/OBS.worker/$name"
+				mkdir -p "$OBS_WORKER_DIRECTORY/$name"
+				mount $i "$OBS_WORKER_DIRECTORY/$name"
 			fi
 			OBS_WORKER_INSTANCES=$(( $OBS_WORKER_INSTANCES + 1 ))
 		done
@@ -130,6 +275,7 @@ case "$1" in
 		INSTANCEMEM=$(( $TOTALMEM / ( 2 * $OBS_WORKER_INSTANCES ) ))
 		echo "OBS_INSTANCE_MEMORY=\"$INSTANCEMEM\"" >> /etc/buildhost.config
 		# append user presets
+		echo "" >> /etc/buildhost.config
 		echo "### preconfigured values from /etc/buildhost.config.presets" >> /etc/buildhost.config
 		cat /etc/buildhost.config.presets >> /etc/buildhost.config
 		
