[dist] improve chown handling in obsstoragesetup

diff --git a/dist/obsstoragesetup b/dist/obsstoragesetup
--- a/dist/obsstoragesetup
+++ b/dist/obsstoragesetup
@@ -154,6 +154,17 @@ case "$1" in
 		[ -d "$backenddir" ] || mkdir -p "$backenddir"
                 if [ -e /dev/OBS/server ]; then
 			mount /dev/OBS/server "$backenddir"
+			if [ -e /usr/lib/obs/server/BSConfig.pm -a -d "$backenddir/run" ]; then
+				# make sure that directories needed by mostly all other daemons are created now
+				# and set proper ownership
+				bsuser=`perl -I/usr/lib/obs/server -MBSConfig -e 'print ( $BSConfig::bsuser || "obsrun" )'`
+				bsgroup=`perl -I/usr/lib/obs/server -MBSConfig -e 'print ( $BSConfig::bsgroup || "obsrun" )'`
+				owner_rundir=`stat -L --printf="%U" "$backenddir/run"`
+				if [ "$owner_rundir" != "root" -a "$owner_rundir" != "$bsuser" ];then
+					uid_rundir=`stat -L --printf="%u" "$backenddir/run"`
+					find $backenddir -uid $uid_rundir -exec chown $bsuser:$bsgroup {} ;
+				fi
+			fi
 			obs_server_size=$(( $(lvdisplay -c OBS/server 2>/dev/null | cut -d: -f7) / 2 / 1024 ))
                 fi
 
@@ -216,10 +227,23 @@ case "$1" in
 				OBS_WORKER_SWAP_SIZE=`round_down_to_pe $OBS_WORKER_SWAP_SIZE $PE_SIZE`
 
 				if [ -z "$OBS_WORKER_ROOT_SIZE" ]; then
+					echo "NUM=$NUM"
 					VG_SIZE=`vgdisplay -c OBS | cut -d: -f16`
-					VG_SIZE=$(( $VG_SIZE * ( $PE_SIZE / 1024 ) ))
-					VG_SIZE=$(( $VG_SIZE - ${obs_server_size:-0} - $OBS_WORKER_CACHE_SIZE - ( $NUM * $OBS_WORKER_SWAP_SIZE ) ))
-					OBS_WORKER_ROOT_SIZE=$(( $VG_SIZE / $NUM ))
+					echo "VG_SIZE=$VG_SIZE"
+					echo "PE_SIZE=$PE_SIZE"
+					PE_SIZE_IN_MB=$((  $PE_SIZE / 1024 ))
+					echo "PE_SIZE_IN_MB=$PE_SIZE_IN_MB"
+					VG_SIZE=$(( $VG_SIZE * $PE_SIZE_IN_MB ))
+					OBS_SERVER_SIZE=${obs_server_size:-0}
+					echo "OBS_SERVER_SIZE=$OBS_SERVER_SIZE"
+					TOTAL_SWAP_SIZE=$(( $NUM * $OBS_WORKER_SWAP_SIZE ))
+					echo "TOTAL_SWAP_SIZE=$TOTAL_SWAP_SIZE"
+					FINAL_VG_SIZE=$(( $VG_SIZE - $OBS_SERVER_SIZE - $OBS_WORKER_CACHE_SIZE - $TOTAL_SWAP_SIZE ))
+					echo "FINAL_VG_SIZE=$FINAL_VG_SIZE";
+					OBS_WORKER_ROOT_SIZE=$(( $FINAL_VG_SIZE / $NUM ))
+					echo "MIN_WORKER_ROOT_SIZE="
+					MIN_WORKER_ROOT_SIZE=$(( 4 * 1024 ))
+					echo "MIN_WORKER_ROOT_SIZE=$MIN_WORKER_ROOT_SIZE"
 					if test $OBS_WORKER_ROOT_SIZE -lt $(( 4 * 1024 )); then
 						echo "ERROR: Not enough space for worker root LVs, just $OBS_WORKER_ROOT_SIZE MB, but at least 4 GB needed."
 						exit 1
@@ -242,6 +266,12 @@ case "$1" in
 				
 						lverr=$(mktemp)
 						if ! lvcreate --wipesignatures y --zero y -n worker_root_${I} -L ${OBS_WORKER_ROOT_SIZE}M OBS ${pvs[$(( $pv_idx + $o1 ))]} 2> $lverr; then
+							if [ $? -gt 0 ];then
+								echo "An error occured while creating LV"
+								cat $lverr
+							else
+								echo "Creation of worker_root_${I} succeed"
+							fi
 							if grep "Insufficient free space" $lverr; then 
 								I=$(( $I - 1 ))
 							else	
@@ -250,6 +280,12 @@ case "$1" in
 							fi
 						else
  				                        lvcreate --wipesignatures y --zero y -n worker_swap_${I} -L ${OBS_WORKER_SWAP_SIZE}M OBS ${pvs[$(( $pv_idx + $o2 ))]} || exit
+							if [ $? -gt 0 ];then
+								echo "An error occured while creating LV worker_swap_${I} "
+								exit 1
+							else
+								echo "Creation of worker_swap_${I} succeed"
+							fi
 						fi
 						rm -f $lverr
 				                pv_idx=$(( $pv_idx + 2 ))
@@ -405,12 +441,7 @@ case "$1" in
 			[ -d $backenddir/run ] || mkdir -p $backenddir/run
 			[ -d $backenddir/log ] || mkdir -p $backenddir/log
 			# fix ownership
-			chown $bsuser:$bsgroup -R $backenddir
-			[ -d $backenddir/gnupg ] && chown -R root:root $backenddir/gnupg
-			[ -d $backenddir/certs ] && chown -R root:root $backenddir/certs
-			[ -f $backenddir/obs-default-gpg.asc ] && chown root:root $backenddir/obs-default-gpg.asc
-			[ -d $backenddir/MySQL ] && chown -R mysql:mysql $backenddir/MySQL
-			[ -d $backenddir/service ] && chown -R obsservicerun:obsrun $backenddir/service
+			chown $bsuser:$bsgroup $backenddir
 		fi
 
 		# offer hook to make random special things in your setup
