[backend] support vmdisk root creation also for emulator mode

diff --git a/dist/obsworker b/dist/obsworker
--- a/dist/obsworker
+++ b/dist/obsworker
@@ -126,11 +126,13 @@ elif [ -e /sys/hypervisor/type ] && grep -q xen /sys/hypervisor/type; then
     OBS_VM_TYPE="xen"
 fi
 
-if [ "$OBS_VM_TYPE" = "xen" -o "$OBS_VM_TYPE" = "kvm" ]; then
+if [ "$OBS_VM_TYPE" = "xen" -o "$OBS_VM_TYPE" = "kvm" -o "${OBS_VM_TYPE#emulator:}" != "$OBS_VM_TYPE" ] ; then
     # we start up in VM mode, check for the worker disk options
-    if [ -n "$OBS_VM_DISK_AUTOSETUP_ROOT_FILESIZE" -a -n "$OBS_VM_DISK_AUTOSETUP_SWAP_FILESIZE" ]; then
+    if [ -n "$OBS_VM_DISK_AUTOSETUP_ROOT_FILESIZE" ]; then
         VMDISK_ROOT_FILESIZE="--vmdisk-rootsize ${OBS_VM_DISK_AUTOSETUP_ROOT_FILESIZE}"
-        VMDISK_SWAP_FILESIZE="--vmdisk-swapsize ${OBS_VM_DISK_AUTOSETUP_SWAP_FILESIZE}"
+        if [ -n "$OBS_VM_DISK_AUTOSETUP_SWAP_FILESIZE" ]; then
+            VMDISK_SWAP_FILESIZE="--vmdisk-swapsize ${OBS_VM_DISK_AUTOSETUP_SWAP_FILESIZE}"
+        fi
         if [ -n "$OBS_VM_DISK_AUTOSETUP_FILESYSTEM" ]; then
             VMDISK_FILESYSTEM="--vmdisk-filesystem ${OBS_VM_DISK_AUTOSETUP_FILESYSTEM}"
         fi
@@ -209,21 +211,21 @@ case "$1" in
             R=$OBS_WORKER_DIRECTORY/root_$I
             # prepare obsworker startup in screen...
             TMPFS=
-            if [ -n "$vmopt" -a "$OBS_VM_TYPE" = "xen" -o "$OBS_VM_TYPE" = "kvm" ]; then
+            if [ "$OBS_VM_TYPE" = "xen" -o "$OBS_VM_TYPE" = "kvm" -o "${OBS_VM_TYPE#emulator:}" != "$OBS_VM_TYPE" ] ; then
                 mkdir -p $R
                 DEVICE="$OBS_WORKER_DIRECTORY/root_$I/root"
-                SWAP="$OBS_WORKER_DIRECTORY/root_$I/swap"
-                if [ -n "$OBS_VM_DISK_AUTOSETUP_ROOT_FILESIZE" -a -n "$OBS_VM_DISK_AUTOSETUP_SWAP_FILESIZE" ]; then
+                if [ -n "$OBS_VM_DISK_AUTOSETUP_ROOT_FILESIZE" ]; then
                     OBS_WORKER_OPT="$OBS_WORKER_OPT1 $VMDISK_AUTOSETUP $VMDISK_ROOT_FILESIZE $VMDISK_SWAP_FILESIZE $VMDISK_FILESYSTEM $VMDISK_MOUNT_OPTIONS $VMDISK_CLEAN"
-                elif [ ! -e "$DEVICE" -o ! -e "$SWAP" ]; then
-                        echo "ERROR: worker is configured to use a VM, but one or all of the following devices/files do not exist: $DEVICE, $SWAP"
-                        exit 1
+                elif [ ! -e "$DEVICE" ]; then
+                    echo "ERROR: worker is configured to use a VM, but the root device do not exist: $DEVICE"
+                    exit 1
+                else
+                  SWAP="--swap $OBS_WORKER_DIRECTORY/root_$I/swap"
                 fi
                 if [ -n "$OBS_VM_USE_TMPFS" ]; then
                     TMPFS="--tmpfs"
                 fi
                 DEVICE="--device $DEVICE"
-                SWAP="--swap $SWAP"
                 MEMORY="--vm-memory $OBS_INSTANCE_MEMORY"
                 if [ -n "$OBS_VM_USE_HUGETLBFS" ]; then
                     HUGETLBFS="--hugetlbfs $OBS_VM_USE_HUGETLBFS"
